import type { Locale } from "@/lib/i18n";

export type DisclaimerBlock = {
  id: string;
  heading: string;
  paragraphs: string[];
  bullets?: string[];
};

export type DisclaimerDocument = {
  title: string;
  intro?: string;
  blocks: DisclaimerBlock[];
};

export type DisclaimerContent = {
  documents: DisclaimerDocument[];
  checkbox: string;
  accept: string;
  decline: string;
  declineNote: string;
  scrollHint: string;
};

const en: DisclaimerContent = {
  documents: [
    {
      title: "Disclaimer (Online Companionship Service / trip-sitter.AI)",
      intro:
        "By using trip-sitter.AI, you confirm that you have read, understood, and agree to this disclaimer.",
      blocks: [
        {
          id: "nature",
          heading: "Nature of the Service",
          paragraphs: [
            "This Service is an AI-driven companionship tool that offers a listening, non-judgmental space when you feel the need to talk, feel lonely, or are experiencing emotional distress.",
            "This Service is NOT:",
          ],
          bullets: [
            "Psychotherapy, counselling, or any form of professional medical service",
            "A tool for mental health diagnosis or clinical assessment",
            "A substitute for a professional psychologist, psychiatrist, social worker, or counsellor",
            "A system that guarantees your safety or guarantees resolution of your difficulties",
          ],
        },
        {
          id: "ai",
          heading: "AI Identity",
          paragraphs: [
            "You are talking to an Artificial Intelligence (AI), not a human being. The system will clearly state this at the start of the conversation. The AI's responses are generated by a language model following preset guidelines, and may contain misunderstandings, omissions, or inaccuracies.",
          ],
        },
        {
          id: "scope",
          heading: "Scope Limitations",
          paragraphs: [],
          bullets: [
            "This Service cannot and will not provide medical diagnoses, medication advice, or treatment plans.",
            "This Service will not conduct in-depth psychological analysis or make professional judgments about the root causes of your difficulties.",
            "If you are experiencing an urgent emotional or mental health crisis, this Service cannot replace professional emergency support.",
          ],
        },
        {
          id: "liability",
          heading: "Limitation of Liability",
          paragraphs: ["To the fullest extent permitted by law:"],
          bullets: [
            "The organisation and developers of this Service shall not be liable for any direct, indirect, incidental, or consequential loss arising from your use of the Service.",
            "You use this Service voluntarily and acknowledge that you understand and accept its nature and limitations.",
            "This Service cannot and does not guarantee continuous availability (e.g. due to system failures or AI provider outages).",
          ],
        },
        {
          id: "pdata-ref",
          heading: "Personal Data",
          paragraphs: [
            "Content you share during conversations may be recorded to maintain conversational memory and improve service quality. Please refer to our Personal Data Collection and Use Notice below and on the Privacy policy page. If you have concerns, please avoid disclosing highly sensitive personal identifying information during conversations.",
          ],
        },
        {
          id: "emergency",
          heading: "Emergency Resources",
          paragraphs: [
            "If you are experiencing thoughts of self-harm, suicidal ideation, or any emotional emergency, please contact immediately:",
          ],
          bullets: [
            "999/911 (or other Emergency services / ambulance)",
            "The Samaritan Befrienders Hong Kong: 2389 2222 (24-hour hotline)",
            "Caritas Family Crisis Support Centre: 18288 (24-hour hotline)",
            "The AI will attempt to provide the above resources when it detects related signals during conversation, but you should not rely solely on the AI to judge emergency situations — if you or someone near you is in danger, please contact the above resources directly or go to the nearest emergency department.",
          ],
        },
      ],
    },
    {
      title:
        "Personal Data Collection and Use Notice (Online Companionship Service / trip-sitter.AI)",
      intro:
        "By using trip-sitter.AI, you confirm that you have read, understood, and agree to this notice.",
      blocks: [
        {
          id: "collect",
          heading: "What We Collect",
          paragraphs: [
            "When you use this Service, we collect:",
          ],
          bullets: [
            "Content you voluntarily provide during conversation (your input messages)",
            "Conversation timestamps",
            "We do not actively request your name, phone number, address, or other identifying information. If you voluntarily disclose such information during conversation, it will be treated as part of the conversation content (see Handling of Conversation Content).",
          ],
        },
        {
          id: "purpose",
          heading: "Purpose of Collection",
          paragraphs: ["We collect the above data solely for:"],
          bullets: [
            "Maintaining the AI's memory within a single conversation, so the conversation flows coherently",
            "Monitoring whether the Service is operating properly (e.g. troubleshooting)",
            "Assisting our organisation's follow-up and support where appropriate (e.g. suspected high-risk cases)",
            "We do not use your conversation content for promotional purposes, market research, or any commercial use.",
          ],
        },
        {
          id: "handling",
          heading: "Handling of Conversation Content",
          paragraphs: [],
          bullets: [
            "Your conversation content is processed by a third-party AI model provider to generate responses.",
            "Conversation content may be briefly stored in our system to maintain memory for that conversation.",
          ],
        },
        {
          id: "retention",
          heading: "Data Retention Period",
          paragraphs: [
            "Conversation memory is generally cleared within 3 months after the conversation ends.",
          ],
        },
        {
          id: "sharing",
          heading: "Third-Party Sharing",
          paragraphs: [
            "We will not transfer or sell your personal data to any third party, except:",
          ],
          bullets: [
            "Necessary data transmission with our AI service provider, required to maintain AI conversation functionality",
          ],
        },
        {
          id: "rights",
          heading: "Your Rights",
          paragraphs: [
            "Under the Personal Data (Privacy) Ordinance, you have the right to:",
          ],
          bullets: [
            "Access personal data we hold about you",
            "Request correction of inaccurate data",
            "Request deletion of your data (subject to legal and safety considerations)",
            "To exercise the above rights, please contact the person in charge.",
          ],
        },
        {
          id: "anonymous",
          heading: "Suggestion for Anonymous Use",
          paragraphs: [
            "Given the emotional nature of this Service, we recommend that you avoid disclosing highly sensitive identifying information (e.g. ID numbers, home address, financial information) during conversation, to protect your own privacy.",
          ],
        },
        {
          id: "amendments",
          heading: "Amendments to This Notice",
          paragraphs: [
            "We may update this notice from time to time. Any material changes will be announced via the Discord announcements channel.",
          ],
        },
      ],
    },
  ],
  checkbox:
    "I have read, understood, and agree to the disclaimer and Personal Data Collection and Use Notice above.",
  accept: "Agree and start chat",
  decline: "Leave",
  declineNote: "You need to agree before using the AI chat.",
  scrollHint: "Scroll to the bottom to read everything before you can agree.",
};

const zhHant: DisclaimerContent = {
  documents: [
    {
      title: "免責聲明（線上陪伴服務 / trip-sitter.AI）",
      intro: "使用即代表你已閱讀、明白並同意本聲明之內容。",
      blocks: [
        {
          id: "nature",
          heading: "本服務之性質",
          paragraphs: [
            "本服務係一個AI驅動嘅陪伴工具，透過人工智能技術，喺你需要傾訴、感到孤單或者情緒困擾嘅時候，提供一個聆聽同陪伴嘅空間。",
            "本服務並非：",
          ],
          bullets: [
            "心理治療、輔導或者任何形式嘅專業醫療服務",
            "精神健康診斷或者臨床評估工具",
            "專業心理學家、精神科醫生、社工或者輔導員之替代品",
            "一個保證你安全或者保證解決你困擾嘅系統",
          ],
        },
        {
          id: "ai",
          heading: "AI身份",
          paragraphs: [
            "你而家對話緊嘅係人工智能（AI），並非真人。系統會喺對話開始時清楚講明呢一點。AI嘅回應由預設嘅語言模型根據既定指引生成，可能存在理解偏差、遺漏或者唔準確嘅情況。",
          ],
        },
        {
          id: "scope",
          heading: "服務限制",
          paragraphs: [],
          bullets: [
            "本服務唔會、亦都唔可以提供醫療診斷、藥物建議或者治療方案",
            "本服務唔會對你進行深度心理分析或者作出關於你困擾根源嘅專業判斷",
            "如果你正經歷緊急嘅情緒或者精神健康危機，本服務唔可以取代專業緊急支援",
          ],
        },
        {
          id: "liability",
          heading: "責任限制",
          paragraphs: ["在法律允許之最大範圍內："],
          bullets: [
            "本機構及本服務開發者，對因使用本服務而引致之任何直接、間接、附帶或衍生損失，概不負責",
            "你自願使用本服務，理解並接受本服務嘅性質同限制",
            "本服務唔會、亦都無法承諾持續可用性（例如系統故障、AI供應商服務中斷等因素）",
          ],
        },
        {
          id: "pdata-ref",
          heading: "個人資料",
          paragraphs: [
            "你喺對話中分享嘅內容，可能會被記錄以維持對話記憶及改善服務質素。詳情請參閱下文《個人資料收集及使用細則》及本網站私隱政策。如你對此有疑慮，請避免喺對話中透露高度敏感嘅個人身份資訊。",
          ],
        },
        {
          id: "emergency",
          heading: "緊急情況資源",
          paragraphs: [
            "如果你正經歷自我傷害念頭、自殺念頭，或者任何緊急嘅情緒危機，請立即聯絡：",
          ],
          bullets: [
            "999/911（或其他熱線緊急報案／召喚救護車）",
            "撒瑪利亞防止自殺會：2389 2222（24小時熱線）",
            "明愛向晴熱線：18288（24小時熱線）",
            "本服務嘅AI會盡力喺對話中偵測到相關訊號時提供以上資源，但唔可以完全依賴AI嚟判斷緊急情況——如果你或者你身邊嘅人正處於危險，請直接聯絡上述資源或者前往最近嘅急症室。",
          ],
        },
      ],
    },
    {
      title: "個人資料收集及使用細則（線上陪伴服務 / trip-sitter.AI）",
      intro: "使用即代表你已閱讀、明白並同意本細則之內容。",
      blocks: [
        {
          id: "collect",
          heading: "我們收集咩資料",
          paragraphs: ["當你使用本服務時，我們會收集："],
          bullets: [
            "你喺對話中主動提供嘅內容（即你所輸入嘅訊息）",
            "對話時間戳記",
            "我們唔會主動要求你提供姓名、電話、地址等身份資料。如果你喺對話中自願透露呢類資訊，該部分內容會被視為對話內容嘅一部分處理（見「對話內容嘅處理」）。",
          ],
        },
        {
          id: "purpose",
          heading: "收集資料嘅目的",
          paragraphs: ["我們收集上述資料，僅用於："],
          bullets: [
            "喺同一次對話入面維持AI嘅記憶，等對話可以連貫",
            "監察服務運作是否正常（例如系統故障排查）",
            "喺有需要時（例如懷疑高風險個案），協助本機構跟進及提供適當支援",
            "我們不會將你嘅對話內容用於推廣、市場調查或者任何商業用途。",
          ],
        },
        {
          id: "handling",
          heading: "對話內容嘅處理",
          paragraphs: [],
          bullets: [
            "你嘅對話內容會經由第三方人工智能服務供應商（AI Model Provider）進行處理，以生成回應",
            "對話內容可能會短暫記錄喺我們嘅系統，以維持該次對話嘅記憶",
          ],
        },
        {
          id: "retention",
          heading: "資料保留期限",
          paragraphs: ["對話記憶一般喺對話結束後3個月內清除"],
        },
        {
          id: "sharing",
          heading: "第三方分享",
          paragraphs: ["我們不會將你嘅個人資料轉交或出售俾任何第三方，除非："],
          bullets: [
            "為維持AI對話功能所需，與人工智能服務供應商之間嘅必要數據傳輸",
          ],
        },
        {
          id: "rights",
          heading: "你嘅權利",
          paragraphs: ["根據《個人資料（私隱）條例》，你有權："],
          bullets: [
            "查閱我哋持有關於你嘅個人資料",
            "要求更正不準確嘅資料",
            "要求刪除你嘅資料（在符合法律及安全考量嘅前提下）",
            "如需行使上述權利，請聯絡負責人。",
          ],
        },
        {
          id: "anonymous",
          heading: "匿名使用建議",
          paragraphs: [
            "由於本服務嘅性質涉及情緒陪伴，我們建議你避免喺對話中透露高度敏感嘅個人身份資訊（例如身份證號碼、住址、財務資料），以保障你自己嘅私隱。",
          ],
        },
        {
          id: "amendments",
          heading: "細則之修訂",
          paragraphs: [
            "我哋可能不時更新本細則，任何重大修訂將透過Discord公告頻道通知使用者。",
          ],
        },
      ],
    },
  ],
  checkbox:
    "我已閱讀、明白並同意以上免責聲明及個人資料收集及使用細則。",
  accept: "同意並開始對話",
  decline: "離開",
  declineNote: "使用 AI 對話前須同意以上內容。",
  scrollHint: "請先滾動至底部，閱讀全部內容後方可同意。",
};

export function getDisclaimerContent(locale: Locale): DisclaimerContent {
  return locale === "zh-Hant" ? zhHant : en;
}

export const DISCLAIMER_STORAGE_KEY = "ts_sitter_disclaimer_v4";
